routes/admin.php
<?php

Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::get('/settings', 'SettingController@index')->name('settings');
            Route::post('/settings', 'SettingController@update')->name('settings.update');
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
                Route::get('ordersAll/invoice', 'OrderController@generateAllInvoice')->name('orders.all.generate');
                Route::get('export', 'OrderController@fileExport')->name('orders.export');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');
            Route::resource('sliders', 'Sliders\SliderController');
            Route::resource('partners', 'Partners\PartnerController');
            Route::post('sliders/save_orders', 'Sliders\SliderController@saveOrders');
            Route::post('partners/save_orders', 'Partners\PartnerController@saveOrders');
            Route::resource('promotions', 'Promotions\PromotionController');
            Route::post('promotions/save_orders', 'Promotions\PromotionController@saveOrders');
            Route::resource('flashes', 'Flashes\FlashController');
            Route::post('flashes/save_orders', 'Flashes\FlashController@saveOrders');
            Route::post('categories/save_orders', 'Categories\CategoryController@saveOrders');
            Route::resource('tags', 'Tags\TagController');
            Route::post('tags/save_orders', 'Tags\TagController@saveOrders');
            Route::resource('mcategories', 'Mcategories\McategoryController');
            Route::post('mcategories/save_orders', 'Mcategories\McategoryController@saveOrders');
            Route::resource('posts', 'Posts\PostController');
            Route::post('posts/save_orders', 'Posts\PostController@saveOrders');
            Route::resource('authors', 'Authors\AuthorController');
            Route::post('authors/save_orders', 'Authors\AuthorController@saveOrders');
            Route::resource('emails', 'Emails\EmailController');
            Route::post('emails/save_orders', 'Emails\EmailController@saveOrders');
            Route::resource('ratings', 'Ratings\RatingController');
            Route::post('ratings/save_orders', 'Ratings\RatingController@saveOrders');

        });
        Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
require 'admin.php';
/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController')->only('index','store','destroy','update');
    Route::resource('wishlist', 'WishlistController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('category');
    Route::get("product/search", 'CategoryController@search')->name('search');
    Route::get("category-list/{slug}", 'CategoryController@getListCategory')->name('category.list');
    Route::get("search", 'ProductController@search')->name('search.product');
    Route::get("{product}", 'ProductController@show')->name('product');

    Route::get("blog/list", 'BlogController@blog')->name('blog');
    Route::get('blog/{slug}', 'BlogController@blogShow')->name('blog.show');
    Route::get('blog/category/{slug}', 'BlogController@findByCategory')->name('blog.category');
    Route::get('blog/tag/{slug}', 'BlogController@findByTag')->name('blog.tag');
    Route::get('blog/author/{slug}', 'BlogController@findByAuthor')->name('blog.author');
    Route::get('page/{slug}', 'BlogController@pageShow')->name('page.show');
});

Route::post('rating/store', 'HomeController@ratingStore')->name('rating.store');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback','Auth\LoginController@handleProviderCallback');
Route::get('api1/cartCount', 'HomeController@cartCount');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.app')
@section('content')
    <!-- Main content -->
    <section class="content">
     
  <div class="box-header">
    <div class="row">
        <div class="col-sm-8">
          
        </div>
        <div class="col-sm-4">


          @if(Session::has('success'))
    <div class="alert alert-info fade in">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{Session::get('success')}}</strong>
     </div>
     @endif
        </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
      
      
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">
              <h3>{{\App\Shop\Posts\Post::count()}}</h3>

              <p>Total Blog Post</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">
              <h3>{{\App\Shop\Products\Product::count()}}</h3>

              <p>Total Products</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">

              <h3> {{\App\Shop\Categories\Category::count()}}</h3>

              <p>Total Categories</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-blue">
            <div class="inner">
              <h3>{{\App\Shop\Employees\Employee::count()}}</h3>
              <p>Total Employees</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
      </div>
      
     <div class="row">
      
      <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-edit"></i></span>

            <div class="info-box-content">
              <span class="info-box-text"><a href="{{route('admin.posts.index')}}"> <i class="fa fa-edit"></i> Blog</a></span>
              <span class="info-box-text"><a href="{{route('admin.authors.index')}}"> <i class="fa fa-user"></i> Author</a></span>
              <span class="info-box-text"> <a href="{{route('admin.mcategories.index')}}"> <i class="fa fa-bars"></i> Blog Category</a></span>
              <span class="info-box-text"><a href="{{route('admin.tags.index')}}"> <i class="fa fa-tag"></i> Tags</a></span>
              
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-gift"></i></span>

            <div class="info-box-content">
            
            <span class="info-box-text"> <a href="{{route('admin.products.index')}}">Products</a> </span>
            <span class="info-box-text"> <a href="{{route('admin.ratings.index')}}">Ratings</a> </span>
            <span class="info-box-text"> <a href="{{route('admin.categories.index')}}">Product Categories</a> </span>
            <span class="info-box-number">{{\App\Shop\Categories\Category::count()}}</span>
            
              
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>       <!-- /.col -->
        
        <div class="col-md-3 col-sm-6 col-xs-12">

          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-users"></i></span>

            <div class="info-box-content">
              <span class="info-box-text"> <a href="{{route('admin.customers.index')}}">Customers</a> </span>
              <span class="info-box-number">{{\App\Shop\Customers\Customer::count()}}</span>
              <span class="info-box-text"> <a href="{{route('admin.customers.create')}}">Create Customer</a> </span>
              
            </div>
            <!-- /.info-box-content -->
          </div>

          <!-- /.info-box -->
        </div>
        <!-- ./col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-ios-people-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text"> <a href="{{route('admin.employees.index')}}"> Employee</a></span>
              <span class="info-box-number">{{\App\Shop\Employees\Employee::count()}}</span>
              <span class="info-box-text"> <a href="{{route('admin.employees.create')}}">Create Employee</a> </span>
              
            </div>
            <!-- /.info-box-content -->
          </div>
          
          <!-- /.info-box -->
        </div>
        
        <!-- ./col -->
      </div>
      <div class="row">
        <!-- ./col -->
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-opencart"></i></span>

            <div class="info-box-content">
            
            <span class="info-box-text"> <a href="{{route('admin.orders.index')}}">List of Order</a> </span>
            <span class="info-box-number">{{\App\Shop\Orders\Order::count()}}</span>
              
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-cogs"></i></span>

            <div class="info-box-content">
            <span class="info-box-text"> <a href="{{ route('admin.settings') }}">Settings</a> </span>
            
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-image"></i></span>
            <div class="info-box-content">
              <span class="info-box-text"> <a href="{{route('admin.sliders.index')}}">Sliders</a> </span>
              <span class="info-box-text"> <a href="{{route('admin.partners.index')}}">Partners</a> </span>
              <span class="info-box-text"> <a href="{{route('admin.promotions.index')}}">Promotions</a> </span>
              <span class="info-box-text"> <a href="{{route('admin.flashes.index')}}">FLash Messages</a> </span>
              
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- ./col -->
  <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-cog"></i></span>

            <div class="info-box-content">
            <span class="info-box-text"> <a href="{{route('admin.attributes.index')}}">Product Attributes</a> </span>
            <span class="info-box-text"><a href="{{route('admin.brands.index')}}">Product Brands</a></span>
              
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>

           
         

        
 
       
          
        
      </div>
    </div>
  </div>
  

    </section>
@endsection